### ISSUE TITLE
14장_전역 변수의 문제점(모듈패턴)

### ISSUE THREAD

**Issue by Ham-mi** [read-modern-js/deep-dive#14]
1. 예제 14-07 var Counter 가 즉시 실행 함수로 묶여 있는데 이게 출력에 큰 차이가 있는지 궁금합니다. 단순히 정보 은닉에만 기능이 있는 건가요? (p.206 참고)
1-1. function() { } 다음에 ( ) 가 한번 더 있는데 왜 있는지 궁금합니다.

예제 14-07 
```javascript
var Counter = (function ( ) {
	var num = 0;

	return {
	   increase () {
		return ++ num;
	   },
	   decrease() {
		return -- num;
	   }
	};
}());

console.log(Counter.num);

console.log(Counter.increase());
console.log(Counter.increase());
console.log(Counter.decrease());
console.log(Counter.decrease());
```

**Comment by yanggak12** [comment]
1-1 . 즉시 실행함수란 () 연산자로 함수 전체를 묶어서 곧바로 실행시키는 함수입니다. 
()가 맨 뒤에 있는것은 곧바로 함수를 호출한다고 생각하시면 됩니다.

> +) 즉시 실행함수
P.177 참고


1) 자바 개발 경험 있으시니 private public 등 접근 제한자를 아주 잘 알고 계실텐데, 자바스크립트에서는 제공하지 않기 때문에 모듈 패턴을 통해 해당 기능을 구현한 것입니다. 즉시 실행 함수 내부를 살펴보겠습니다.
<code>var num = 0;</code> 가 있는데, 해당하는 함수의 스코프 내부에서 생성된 지역 변수 num은 함수 종료 시 그 생명 주기도 종료됩니다.
하지만 앞선 질문에서 말씀드렸다시피 함수 반환을 통해 해당 지역 변수의 값을 꺼내어 사용할 수 있는데 그것을 활용하는 패턴이 모듈 패턴입니다. 정리하면, private 접근 제한자 대신 지역 변수의 생명주기를 활용하는 것이고, 반환을 통해 public으로 사용하는 것처럼 구색을 맞추는 것입니다.

잘못된 부분이나 피드백 있으면 아래 comment로 남겨주세요!
