### ISSUE TITLE
15장_let, const 키워드와 블록 레벨 스코프(변수 호이스팅_let)

### ISSUE THREAD

**Issue by Ham-mi** [read-modern-js/deep-dive#15]
1. 예제 15-10에서 하위에서 상위 스코프의 변수를 가져올수 있다고 하는데 어째서 참조 에러(ReferenceError)가 발생하나요? 1이 출력되야 하지 않나요? 호이스팅이 발생했다는 것은 지역변수인 `let foo = 2` 가 작동했다는 것이고 그렇다면 2라도 출력 되야하는 것이 아닌가요? (p.213 참고)

```javascript
let foo = 1;

{
	console.log(foo);
	let foo = 2;
 }
```

**Comment by yanggak12** [comment]
let은 블록 레벨 스코프입니다.
블록 레벨 스코프는 모든 코드 블록을 지역 스코프로 인정합니다.
코드 블록에서 지역변수 foo가 호이스팅 되었고, 
스코프의 시작 지점부터 초기화 시작 지점까지 변수를 참조할 수 없는 구간인 
TDZ(일시적 사각지대)에 위치하기 때문에 ReferenceError를 띄우는게 맞습니다.
