### ISSUE TITLE
13장_스코프(스코프와 네임스페이스의 관계)

### ISSUE THREAD

**Issue by Dinogarlic** [read-modern-js/deep-dive#16]
p.192에 "즉, 스코프는 네임스페이스다."라는 문장이 있는데, 이 문장의 의미가 무엇인가요?

**Comment by yanggak12** [comment]
네임스페이스는 변수 이름이나 함수 이름과 같이 명칭 즉, 식별자를 사용하는 공간으로 소속을 나타낸다고 표현할 수 있습니다.
스코프가 다른 경우 같은 식별자를 선언할 수 있다는 뜻이에요.
아주 간단한 예를 들면,
```javascript
const name = 'Yoonsang';
  
function sayName ( inputName ){
  const name = inputName;
  return name;
}

sayName(name);
```
위 코드는 전역 상수로 name이라는 식별자를 사용하여 선언했는데,
sayName이라는 함수 내부에서 name이라는 상수를 또 선언해서 사용합니다.
이렇게 선언해도 스코프가 다르기 때문에 정상적으로 작동합니다.
즉, 같은 식별자를 사용해도 자바스크립트 엔진이 구분해서 식별자 결정을 할 수 있게 하는 스코프를 네임스페이스로 볼 수 있다 이런 뜻입니다.

답변이 되었으면 좋겠네요.
추가 의견이나 피드백은 아래 코멘트로 남겨주세요.
