### ISSUE TITLE
14장_전역 변수의 문제점(대체방법 중 모듈 패턴)

### ISSUE THREAD

**Issue by Dinogarlic** [read-modern-js/deep-dive#17]
p.206 <14.3.3 모듈 패턴>
1. 모듈 패턴이 전역 변수를 대체하는 것이 잘 이해가 가지 않는데 설명해주실 수 있나요?
2. 변수가 외부로 노출되지 않는다는 점을 제외하고, 함수 내에서 선언된 지역 변수와 어떤 차이점이 있나요?

**Comment by yanggak12** [comment]
1. 모듈 패턴은 전역변수를 대체하는것이 아니라 전역 변수를 억제하는 기능을 합니다. 
이 부분은 책에도 나와있지만 클로저에 대한 이해가 필요합니다.
저도 확실하지 않지만 간단하게 설명드리면,
```javascript
function nameFunc(){
  const name = 'Yoonsang';
  function displayName() {
    console.log(name);
  }
  return displayName;
}

const yys = nameFunc;
yys(); // Yoonsang
```
  위 코드를 보면 nameFunc 함수 내부의 <code>name</code>변수가 yys() 함수 호출 시에도 남아서 Yoonsang을 출력합니다.
  자바스크립트는 함수를 리턴하고, 리턴하는 함수가 클로저를 형성합니다. 이 환경은 클로저가 생성된 시점의 스코프 내에 있는 모든 지역 변수로 구 
 성됩니다. 
  yys는 nameFunc이 실행될 때 생성된 displayName 함수의 인스턴스에 대한 참조입니다. displayName의 인스턴스는 변수 name이 렉시컬 
  스코프에 의해 연결되어 있습니다. 그렇기 때문에 Yoonsang을 출력할 수 있었습니다.
  저는 이런 느낌으로 전역변수를 억제한다는 느낌으로 이해했습니다만 나중에 24장을 더 자세히 살펴보면서 이해하면 좋을 것 같습니다.

2. 함수 내에서 선언된 지역 변수를 함수 외부에서 참조할 수 없는 특성을 **변수가 외부로 노출되지 않는다**고 표현한 것이고, 모듈 패턴은 이러한 점을 이용해 즉시 실행 함수로 감싸 private 접근 제한자를 붙인 것과 마찬가지의 효과를 내어줍니다.
함수 내에서 선언 된 지역 변수와 차이가 있는 게 아니라 그것을 활용하는 것입니다.

잘못된 부분이나 피드백, 추가 의견 등은 아래 코멘트로 남겨주세요.
