### ISSUE TITLE
Round3. 핵심요약 (신지령)

### ISSUE THREAD

**Issue by bluenight29** [read-modern-js/deep-dive#24]
- 스코프란?
    - 자신을 참조할 수 있는 식별자가 유효한 범위를 스코프라한다.
        
        
- 렉시컬 환경
    - 코드가 어디서 실행되며 주변에 어떤 코드가 있는
        
        
- 블록레벨 스코프
    - 함수 뿐만아니라 코드블록에서도 지역스코프를 만드는 것
    - ※ var는 함수코드블록만  지역스코프로 인정
- 동적 스코프 vs 렉시컬 스코프
    - 동적 스코프
        - 함수를 어디서 호출했는지에 따라 함수의 상위스코프를 결정
    - 렉시컬 스코프
        - 함수를 어디서 정의했는지에 따라 함수의상위 스코프 결정
            
            

- let 변수
    - 재할당이 필요한 경우에 한정해 사용
    - 변수 호이스팅이 발생하지 않는 것처러 동작하지만 그렇지 않다.
- const 변수
    - 재할당이 금지된 변수
    - 선언과 동시에 초기화해야함
    - 변수 호이스팅이 발생하지 않는 것처러 동작하지만 그렇지 않다.

**Comment by Ham-mi** [comment]
렉시컬 환경은 스코프와 식별자를 관리한다. 즉, 렉시컬 환경은 스코프를 구분하여 식별자를 등록하고 관리하는 저장소 역할을 하는 렉시컬 스코프의 실체 이다. 렉시컬 환경 안에 렉시컬 스코프가 있습니다.
