### ISSUE TITLE
05장_표현식과 문

### ISSUE THREAD

**Issue by Ham-mi** [read-modern-js/deep-dive#3]
1. 세미 콜론은 반드시 붙여야 하는가? (p.55~56참고)
1-1. 그 이유는?

**Comment by yanggak12** [comment]
책에서 세미콜론을 반드시 붙여야 한다고 하고 있지 않고 책에서 정한 규칙이 **우리는 세미콜론을 붙입시다** 인 것 같아요.

옛날에는 지금 같이 코딩을 하는 정해져있는 규칙이 없었다고 합니다.
그래서 막 코딩하는게 제각각이었다고 하는데
누구는 줄바꿈이 전혀 없이 한줄에 모든 코드를 작성하는 사람이 있었다고 합니다.
그때 한줄에 있는 코드들을 세미콜론을 통해 분리하고 명령들을 분리할 수 있는 유일한 수단이 세미콜론인데 
js에서는 필수가 아닙니다.

마치 우리가 문자열 리터럴을 할당할때 작은 따옴표(') 를 쓰거나 큰 따옴표(")를 쓰거나 상관 없는것 처럼요!
근데 이러한 부분들은 협업할때 용이하기 위해서 ESLint 와 Prettier로 통일화해주는게 좋다고 합니다!!

ESLint Prettier 규칙은 커스텀이 가능하니 세미콜론을 붙일지 말지는 
사람들하고 같이 맞추면 좋을것 같습니다.

**[결론]
저희 스터디 예제코드 커밋에도 세미콜론을 붙입시다. ㅎㅎ**

**Comment by gymdong** [comment]
자바스크립트에서 세미콜론을 반드시 붙일 필요는 없는 것 같습니다. 
그렇지만 책의 예제에서도 나왔듯이, 편의를 위해 세미콜론을 붙이지 않아서 개발자의 의도와 코드가 다르게 실행될 수 있는 상황이 존재합니다. 흔하지 않은 상황이라도 사람은 반드시 실수를 할 수 밖에 없기 때문에 거대한 프로젝트 상황이라면 작은 오류가 전체 흐름을 망가트릴 수도 있습니다. 
그렇기 때문에 세미콜론을 붙여야 한다는 주장이 다수를 차지하고 있기도 하고, 책에서도 세미콜론을 붙이기로 했기 때문에 웬만해서는 세미콜론을 붙이는 것이 좋을 것 같습니다. 
물론 협업을 하는 상황에서는 그 멤버들끼리 어떤 규칙을 설정하여 맞추면 좋을 것 같습니다.
