### ISSUE TITLE
코드 한 줄의 의미를 모르겠습니다..!!

### ISSUE THREAD

**Issue by Dinogarlic** [read-modern-js/deep-dive#30]
p233
코드 한 줄 의미를 모르겠습니다!!
Object.keys(target).forEach(key => deepFreeze(target[key]));

재귀적으로 호출되는 과정에 대해서 설명해주실 수 있나요..?

**Comment by Ham-mi** [comment]
```javascript
function deepFreeze(target) {
	//객체가 아니거나 동결된 객체는 무시하고 객체이고 동결되지 않은 객체만 동결한다.
    if(target && typeof target === 'object' && !Object.isFrozen(target)){
    	console.log(target);
        Object.freeze(target);
        Object.keys(target).forEach(idx => deepFreeze(target[idx]));
        // 배열을 순회하며 각 요소에 대해 콜백 함수를 실행한다.
    }
    return target;
}

const person = {
	name: 'Lee',
    address: { city: 'Seoul' }
};

deepFreeze(person);
// {name:'Lee', address : {}}
// { city : 'Seoul' }

```
key를 idx라 생각하시고 target 배열에 넘버링을 해줬다고 생각하시면 편할 것 같습니다!
처음 1회차에 name 과 address가 들어가고 그 배열의 객체들을 살펴보게 됩니다. 
살펴본 객체가 만약 객체를 가지고 있다면 key로 받아 deepFreeze를 다시 실행시켜줍니다.
address를 예시로 들면 key = > deepFreeze(target[key]) 이부분이 deepFreeze(address[city]) 처럼 들어가게 됩니다.
자기 자신을 참조하여 다시 실행시키는 이부분이 재귀적으로 호출되는 과정입니다.
2회차에서는 city 가 들어가고 그 배열의 객체들을 살펴 보게 됩니다. 
모두 들어가고 이미 freeze가 되었다면 더이상 재귀가 실행되지 않고 return으로 반환하게 됩니다.
