### ISSUE TITLE
06장_데이터 타입

### ISSUE THREAD

**Issue by Ham-mi** [read-modern-js/deep-dive#4]
1. 자바스크립트는 왜 동적타이핑 언어가 되었을까?
  1-1 왜 굳이 변수 선언시 타입을 두지 않았을까?

**Comment by Ham-mi** [comment]
-> 추측. 자바스크립트는 컴파일 작업을 수행하지 않는 인터프리터 언어다. 정적 타입 언어는 컴파일 시점에서 선언한 데이터 타입에 맞는 값을 할당했는지 검사 하는 타입 체크를 수행한다. 자바스크립트는 이 과정을 실행 하지 않음으로써(타입 체크를 하지 않음)  처리속도를 빠르게 만드는 선택을 하지 않았나 추측한다.

=>  대부분의 모던 자바 스크립트 엔진은 이터프리터와 컴파일러의 장점을 결합해 비교적 처리 속도가 느린 인터프리터의 단점을 해결했다. 인터프리터는 소스코드를 즉시 실행하고 컴파일러는 빠르게 동작하는 머신 코드를 생성하고 최적화 한다. 이를 통해 컴파일 단계에서 추가적인 시간이 필요함에도 더욱 빠르게 코드를 실행 할 수 있다. (p.14 2.5 자바스크립트 특징 참고 )

**Comment by gymdong** [comment]
제 생각에는, 먼저 자바스크립트는 인터프리터 언어이므로 개발자가 별도의 컴파일을 진행하지 않습니다. 최근 자바스크립트 엔진에서는 컴파일러와 인터프리터의 장점을 결합하고 있지만, 명백하게 따지면 자바스크립트는 런타임에 컴파일되며 인터프리터 없이는 실행할 수 없기에 컴파일러 언어는 아닙니다. 그리고 정적 타이핑 언어는 타입 체크를 컴파일 시간에 진행하므로 자연스럽게 인터프리터 언어이기 때문에 동적 타이핑이 된 것일수도 있겠습니다. 정적 타이핑이면서 인터프리터 언어인 경우는 아직 없기 때문입니다. 
 말씀하신 것처럼 동적 타이핑을 선택하여 처리 속도를 빠르게 한 것도 하나의 이유일 수 있겠습니다.  하지만 코드의 실행 속도 자체는 정적 타이핑이 더 빠른 편이기 때문에 '처리속도를 빠르게 만드는 선택' 이라는 부분은 생각의 여지가 있어 보입니다.

이것은 장점일수도, 단점일수도 있을 것 같습니다. 그래서 최근에는 이것을 보완한 타입스크립트가 사용되고 있는 모습도 꽤 있는 것으로 보입니다.
