### ISSUE TITLE
Round 6. 핵심요약 (양윤상)

### ISSUE THREAD

**Issue by yanggak12** [read-modern-js/deep-dive#44]
# 2월12일 정리

### 클로저

클로저는 일반적으로 중첩 함수가 상위 스코프의 식별자를 참조하고 있고 중첩 함수가 외부 함수보다 더 오래 유지되는 경우에 한정하는 중첩함수를 의미한다.

- 자유 변수 : 클로저에 의해 참조될 수 있는 변수
- 상태를 안전하게 변경하고 유지하기 위해 사용 - 은닉: 특정 함수에게만 상태 변경을 허용하여 의도치 않게 변경되는 경우를 사전에 차단.
- 캡슐화 : 객체의 상태를 나타내는 프로퍼티와 프로퍼티를 참조하고 조작할 수 있는 메소드를 하나로 묶음, 객체의 특정 프로퍼티나 메소드를 은닉하여 정보를 보호하고, 객체간의 상호 의존성(결합도)를 낮추는 효과
- '#' 으로 private 접근 제한자 설정 가능(뒤에서 계속)

### 클래스

기존 객체지향 프로그래밍 언어 경험자들에게 편리하고 익숙하게 제공되는 객체 생성 메커니즘

- 일반적으로 파스칼 케이스
- 일급 객체
- 클래스 호이스팅
    - let, const와 같이 TDZ에 위치
- 클래스는 반드시 new 연산자와 함께 사용해야 인스턴스 생성이 가능하다. (함수가 일반 함수로 호출되는것과 다름)
- 클래스 표현식에서 사용한 클래스 이름은 해당 스코프에만 존재하게 되어 외부 코드에서 접근 불가능
- 기본적으로 strict mode
- 클래스 몸체에 정의할 수 있는 메소드 : constructor 메소드, 프로토타입 메소드, 정적 메소드
    - constructor 메소드
        - 인스턴스를 생성하고 초기화하기 위한 특수한 메소드
        - constructor 내부에서 this에 추가한 프로퍼티는 인스턴스 프로퍼티가 됨. 즉, this는 인스턴스
        - 생략시 암묵적으로 빈 constructor가 정의됨. 단, 인스턴스 초기화 위해서는 생략 X
        - 내부에서 return문을 반드시 생략
    - 프로토타입 메소드
        - 클래스가 생성한 인스턴스는 기본적으로 프로토타입 체인의 일원이 됨
    - 정적 메소드
        - 명시적으로 생성자 함수에 메소드를 추가해야함
        - static 키워드를 메소드 앞에 붙이기
        - 클래스에 바인딩됨.
        - 인스턴스의 프로토타입 체인상에 클래스가 존재하지 않기 때문에 인스턴스로 호출할 수 없음.
- 클래스의 인스턴스 생성과정
    1. 인스턴스 생성과 this 바인딩
    2. 인스턴스 초기화
    3. 인스턴스 반환
- 상속
    - 상속받아 새로운 클래스로 확장가능
    - <<클래스>> extends <<[[Construct]]내부 메소드를 갖는 함수객체로 평가될 수 있는 모든 표현식>>
    - super 호출
        - 수퍼 클래스의 constructor를 호출한다.
        - 서브 클래스에서 constructor를 생략하지 않은 경우 서브 클래스의 constructor에서는 반드시 super를 호출
        - super를 호출하기 전에는 this를 참조할 수 없음
        - super는 반드시 서브클래스의 constructor에서만 호출
    - super 참조
        - 메서드 내 super를 참조하면 수퍼클래스의 메소드를 호출할 수 있다.
- 상속 클래스 인스턴스 생성과정
    1. 서브 클래스 super 호출
    2. 수퍼클래스의 인스턴스 생성과 this 바인딩
    3. 수퍼클래스의 인스턴스 초기화
    4. 서브클래스 constructor로의 복귀와 this 바인딩
    5. 서브클래스의 인스턴스 초기화
    6. 인스턴스 반환
    

### ES6 함수

ES6에서 메서드에 대한 정의가 명확하게 규정되었다. 

- 메서드 축약 표현으로 정의된 함수를 의미
- 화살표 함수
    - 객체 리터럴을 반환하는 경우 객체 리터럴을 소괄호로 감싸주어야한다.
        - 아니면 return을 명시적으로 해주기
    - 중복된 매개변수 이름 금지
    - 화살표 함수 자체 this, arguments, super, new.target 바인딩을 갖지 않음.
        - 상위 스코프를 참조한다.
    - 메서드를 화살표함수로 정의하는것은 피하기 (this 바인딩 문제)
        - ES6 메서드 축약 표현으로 정의한 메서드 사용하기
- Rest 파라미터
    - 함수에 전달된 인수들의 목록을 배열로 전달
    - 단 하나만 선언하기
    - length 프로퍼티에 영향을 주지 않음
- 매개변수 기본값 할당
    - 기본값으로 방어 코드 작성 가능

**Comment by gymdong** [comment]
```
var obj1 = {
  method1() {
    console.log("method 1");
  }
}

var obj2 = {
  method2() {
   super.method1();
  }
}

Object.setPrototypeOf(obj2, obj1);
obj2.method2(); // logs "method 1"
```

**Comment by gymdong** [comment]
https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Operators/super
