### ISSUE TITLE
Array.from의 콜백 함수 자세히 살펴보기

### ISSUE THREAD

**Issue by yanggak12** [read-modern-js/deep-dive#48]
503페이지
예제 27-29 내용
```javascript
Array.from({length : 3}, (_, i) => i); // [0, 1, 2]
```
위처럼 콜백함수의 두번째 인수가 리턴되어 배열을 출력하는데,
첫번째 인수로 할 수 있는게 무엇일까요? 왜 있을까요..

<img width="482" alt="스크린샷 2022-02-18 오후 10 49 46" src="https://user-images.githubusercontent.com/46489446/154694839-b32310bd-7047-4eaa-9538-bfaa6fdc1835.png">

**Comment by yanggak12** [comment]
https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Array/from
```javascript
// Generate a sequence of numbers
// Since the array is initialized with `undefined` on each position,
// the value of `v` below will be `undefined`
Array.from({length: 5}, (v, i) => i);
// [0, 1, 2, 3, 4]
```
각 위치마다 undefined로 초기화 시켜주는 용도라고 하네요!
[empty, empty, empty] 를 방지하기 위함일까요?
다들 어떻게 생각하시나요?!

**Comment by gangmin2** [comment]
Array.from 메서드에서 인덱스를 참조하려면 두 개의 매개변수가 필요합니다.
`
    Array.from({length: 5})    // [ undefined, undefined, undefined, undefined, undefined ]

    Array.from({length: 5}, (i) => i)    // [ undefined, undefined, undefined, undefined, undefined ]

    Array.from({length: 5}, (v, i) => i)    // [ 0, 1, 2, 3, 4 ]
`
위와 같이 v 없이 i만 사용하게 된다면 i를 인덱스가 아닌 값으로 인식하게 되고 {length: 5}로 만들어진 배열의 값인 undefined만 출력하게 되는 것입니다.

즉 첫 번째 인수를 사용하는 이유는 인덱스 값에 접근하기 위함인 것 같습니다.

참고 : https://perlpark.github.io/articles/array-from/
