### ISSUE TITLE
Array.prototype.sort 순서 질문

### ISSUE THREAD

**Issue by gymdong** [read-modern-js/deep-dive#54]
![unknown](https://user-images.githubusercontent.com/61023613/154787578-62db7e58-6f70-4d1e-86bb-1e4a7518fd36.png)

여기서 a, b, a-b를 출력했을때 나오는 정렬의 순서가 왜 저렇게 나오는지 이해가 잘 안되네요 ㅠㅠ

**Comment by yanggak12** [comment]
```javascript
const arr = [3, 1, 2, 4, 5];

const newArr = arr.sort((a, b) => {
  console.log(a, b, a - b);
  return a - b; // 일반적으로 대부분 정렬이 되어 있으니까,큰 수에서 작은 수를 빼는게 큰 리소스 소모가 없어서 결정했나?
});

console.log(newArr);


```


> 1 3 -2
2 1 1
2 3 -1
2 1 1
4 2 2
4 3 1
5 3 2
5 4 1
[1,2,3,4,5]

그렇네요. 뒤에 인수가 a에 먼저 들어오네요 🤩
