### ISSUE TITLE
12장 콜백 함수와 관련한 질문입니다.

### ISSUE THREAD

**Issue by gymdong** [read-modern-js/deep-dive#8]
```
res = [1,2,3].reduce(function(acc,cur) {
    return acc+cur;
},0);
console.log(res)
```
P186, 콜백함수에서 이런 예제 코드가 있었습니다.
여기서 reduce 메서드의 두 번째 인수로 0을 전달했는데, 여기서 0이 무슨 역할인지 궁금합니다. map와 filter 메서드에는 이것을 전달하지 않았기 때문에 초기값이라고 생각되는데요, 그렇다면 이것을 전달했을 때와 전달하지 않았을 경우에 콜백 함수의 실행 횟수 차이가 있는지도 궁금합니다.

**Comment by Ham-mi** [comment]
reduce()는 **reduce(콜백함수, 초기값)**와 같은 형태를 가지고 있으며 여기서 두번째 인수 0은 초기 값에 해당합니다. 초기값은 최초의 리듀서(콜백함수)의 호출에서 누산기에 제공하는 값입니다. 초기값이 없으면 배열의 첫번째 요소(0번 인덱스)를 사용하고 초기 값이 있다면 주어진 초기값을 사용합니다.

초기값을 전달하지 않았을때 발생할 수있는 경우에는 1. 배열의 첫번째 요소(0번 인덱스)를 누산기에 누적한 후 1번 인색스 부터 reducer를 거칩니다. 2. 배열의 요소 값이 1개 인데도 초기값을 제공하지 않은 경우 이거나 초기값은 있지만 배열이 빈 배열인 경우에는 그 단독 값을 reducer을 거치지 않고 바로 반환합니다. 3. 배열이 비었는데도 초기값이 없는 없는 상태에서 reduce()를 호출하면 TypeError 오류가 발생합니다.

이렇게 초기값을 주지 않으면 발생할 수 있는 경우의 수가 3가지이므로 초기값은 주어지는 것이 안전합니다.
`const sumCallback = (acc, cur ) = > { return acc + cur}; 

//초기값 없이 reduce()실행할 경우 3가지
[1,2,3].reduce ( sumCallback ); // 1 + 2 + 3 = 6 : 초기 값이 없으므로 0번 인덱스를 누적기에 누적
[1].reduce( sumCallback ); // 1 : 배열의 요소 값이 1개 이고 초기 값이 X
[].reduce( sumCallback, 1 ); // 1 : 빈 배열에 초기값 1
[ ].reduce( sumCallback ); // TypeError ` 

실행 횟수 차이의 경우
배열에 [0,1,2,3,4] 가 있을 때, 초기 값이 없는 경우, 초기 값이 없기 때문에, 누산기에 **배열의 첫번째 값이 들어간 상태로** 배열의 두번째 값 부터 reducer를 거치기 시작합니다. 따라서 콜백함수(reducer) 호출은 **4번**만 실행됩니다. 하지만, 초기값이 주어지는 경우, 누산기에 초기값이 있기 때문에 주어진 **배열의 첫번째 값인 0부터** reducer를 거치기 시작합니다. 따라서, 콜백함수(reducer)는 **5번** 실행됩니다.
